spring:
  application:
    name: bankcore
  datasource:
    url: jdbc:mysql://localhost:3306/bankcore
    username: bankcore
    password: bankcore_password
  jpa:
    hibernate:
      ddl-auto: validate
